background            #303446
foreground             #c6d0f5
cursor                 #c6d0f5
selection_background   #414559
selection_foreground   #c6d0f5
color0                 #303446
color8                 #292c3c
color1                 #e78284
color9                 #e78284
color2                 #a6d189
color10                #a6d189
color3                 #e5c890
color11                #e5c890
color4                 #8caaee
color12                #8caaee
color5                 #ca9ee6
color13                #ca9ee6
color6                 #81c8be
color14                #81c8be
color7                 #b5bfe2
color15                #c6d0f5
active_border_color    #ca9ee6
inactive_border_color  #292c3c
active_tab_background  #303446
active_tab_foreground  #ca9ee6
inactive_tab_background #292c3c
inactive_tab_foreground #b5bfe2
url_color               #ca9ee6
